trigger:
  - master
parameters:
  - name: keyvault_name
    displayName: Keyvault Name
    type: string
    default: testakv12345 
  - name: secret_name
    displayName: Secret name
    type: string
    default: test
  - name: secret_value
    displayName: Secret value
    type: string
    default: test123
pool:
  vmImage: windows-latest
steps:
 - task: AzurePowerShell@5
   inputs:
     azureSubscription: 'Pay-As-You-Go(6cff3a05-dfaf-45ce-ae38-3521a14c2cf7)'
     ScriptType: 'InlineScript'
     Inline: |
       $secretvalue = ConvertTo-SecureString ${{parameters.secret_value}}  -AsPlainText -force
        $secret = Set-AzKeyVaultSecret -VaultName ${{parameters.keyvault_name}} -Name ${{parameters.secret_name}}  -SecretValue $secretvalue