 # ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

parameters:
  - name: keyvault_name
    displayName: Keyvault Name
    default: " *** put keyvault name here ***"
    type: string
  
  - name:
    displayName: Secret name
    default: " *** put secret name here ***"
    type: string
    

  - name: secret_value
    displayName: Secret value
    default: " *** put secret value here ***"
    type: string

pool:
  vmImage: 'windows-latest'

steps:
   - task: PowerShell@2
     inputs:
      targetType: 'inline'
      script: |
        $secretvalue = ConvertTo-SecureString ${parameters.secret_value} -AsPlainText -force
        
        $secret = Set-AzKeyVaultSecret -VaultName ${parameters.keyvault_name} -Name ${parameters.secret_name}  -SecretValue $secretvalue
