trigger:
  - master
parameters:
  - name: keyvault_name
    displayName: Keyvault Name
    type: string
  - name: null
    displayName: Secret name
    type: string
  - name: secret_value
    displayName: Secret value
    type: string
pool:
  vmImage: windows-latest
steps:
  - task: PowerShell@2
    inputs:
      targetType: inline
      script: >
        $secretvalue = ConvertTo-SecureString ${parameters.secret_value}
        -AsPlainText -force


        $secret = Set-AzKeyVaultSecret -VaultName ${parameters.keyvault_name}
        -Name ${parameters.secret_name}  -SecretValue $secretvalue
